# syntax=docker/dockerfile:1

## Creates a Docker image for Spring Boot Application that can be debugged remotely
FROM maven:3.8.4-jdk-11-slim as BUILD

# Set the current working directory inside the image
WORKDIR /app

# Copy maven wrapper and dependencies
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Run maven and install dependencies into image
RUN mvn dependency:go-offline -B

# Copy the project source
COPY src ./src

# Run Command
ENTRYPOINT ["sh", "docker/entrypoint.sh"]
